version: 1
tool_paths:
  uaft: null
  csvtools_root: null
  perfreporttool: null
cache:
  directory: .cerebrus-cache
  max_entries: 50
profiles:
  - name: default
    report_type: summary
    csv_filters:
      - stat=Unit
    description: Default profiling profile.
